name: dartfield
description: A simple and customizable Dart implementation of BitField that uses enum to represent bits.
version: 1.1.0
repository: https://github.com/kasefuchs/dartfield
issue_tracker: https://github.com/kasefuchs/dartfield/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
